// This file is auto-generated by NSwag. Do not edit manually.
// Regenerate with: npm run generate-types
// Source: OE2EmpireTracker.Common + OE2EmpireTracker.Server assemblies

// ============================================================
// Server & Character Models
// ============================================================

export interface ServerFaction {
  uuid: string;
  name: string;
  leaderCharacterUUID: string;
  memberUUIDs: string[];
}

export interface ServerCharacter {
  uuid: string;
  name: string;
  factionUUID: string | null;
  role: TokenRole;
}

export interface ApiToken {
  token: string;
  characterUUID: string;
  role: TokenRole;
  createdAt: string;
  expiresAt: string | null;
}

export type TokenRole = 'Owner' | 'FactionLeader' | 'Character';

// ============================================================
// Faction Permission Models
// ============================================================

export interface FactionCapability {
  factionUUID: string;
  capabilities: string[];
}

export type FactionClearanceLevel = 'None' | 'Read' | 'Write' | 'Admin';

export interface FactionPermissionGroup {
  uuid: string;
  name: string;
  clearanceLevel: FactionClearanceLevel;
  capabilities: FactionGroupCapability[];
  sharingRules: FactionGroupSharingRule[];
}

export interface FactionGroupCapability {
  dataType: DataType;
  allowed: boolean;
}

export interface FactionGroupSharingRule {
  targetType: SharingTargetType;
  targetUUID: string;
  dataTypes: DataType[];
}

export interface FactionMemberPermissions {
  characterUUID: string;
  groupUUID: string;
  capabilities: FactionMemberCapability[];
}

export interface FactionMemberCapability {
  dataType: DataType;
  allowed: boolean;
}

// ============================================================
// Character Permission Models
// ============================================================

export interface CharacterCapability {
  characterUUID: string;
  capabilities: string[];
}

export type CharacterClearanceLevel = 'None' | 'Read' | 'Write' | 'Admin';

export interface CharacterPermissionGroup {
  uuid: string;
  name: string;
  clearanceLevel: CharacterClearanceLevel;
  capabilities: CharacterGroupCapability[];
  sharingRules: CharacterGroupSharingRule[];
}

export interface CharacterGroupCapability {
  dataType: DataType;
  allowed: boolean;
}

export interface CharacterGroupSharingRule {
  targetType: SharingTargetType;
  targetUUID: string;
  dataTypes: DataType[];
}

export interface CharacterGranteePermissions {
  granteeUUID: string;
  granteeType: GranteeType;
  capabilities: CharacterGranteeCapability[];
}

export interface CharacterGranteeCapability {
  dataType: DataType;
  allowed: boolean;
}

export type GranteeType = 'Character' | 'Faction' | 'Public';

// ============================================================
// Intel & Audit Models
// ============================================================

export interface IntelComment {
  uuid: string;
  authorCharacterUUID: string;
  content: string;
  createdAt: string;
  factionShares: IntelCommentFactionShare[];
}

export interface IntelCommentFactionShare {
  factionUUID: string;
  sharedAt: string;
}

export interface PermissionAuditEntry {
  uuid: string;
  timestamp: string;
  actorCharacterUUID: string;
  actionType: PermissionActionType;
  targetUUID: string;
  dataType: DataType;
  details: string;
}

export type PermissionActionType = 'Grant' | 'Revoke' | 'Modify' | 'Create' | 'Delete';

export type DataType = 'Colonies' | 'Blueprints' | 'Surveys' | 'Profiles' | 'Intel';

// ============================================================
// Sharing Models
// ============================================================

export interface SharingRule {
  uuid: string;
  ownerCharacterUUID: string;
  targetType: SharingTargetType;
  targetUUID: string;
  dataTypes: DataType[];
  createdAt: string;
}

export type SharingTargetType = 'Character' | 'Faction' | 'Public';

export type MembershipAction = 'Add' | 'Remove' | 'Promote' | 'Demote';

export type MembershipActionType = 'Join' | 'Leave' | 'Kick' | 'Invite';

// ============================================================
// Colony Planner Models
// ============================================================

export interface ColonyPlannerRequest {
  structures: PlannerStructure[];
  items?: Record<string, number>;
  playerSkills?: Record<string, number>;
}

export interface ColonyStatusResult {
  powerProvided: number;
  powerRequired: number;
  habitationProvision: number;
  habitationRequired: number;
  foodProvision: number;
  foodRequired: number;
  entertainmentProvided: number;
  entertainmentRequired: number;
  warehouseCapacity: number;
  warehouseRequired: number;
}

export interface BuildOrderResult {
  steps: BuildOrderStep[];
  totalTimeEstimate: string;
}

export interface BuildOrderStep {
  sequence: number;
  structureName: string;
  blueprintType: string;
  resourcesRequired: ResourceRequirement[];
  timeEstimate: string;
}

export interface ResourceRequirement {
  resourceName: string;
  quantity: number;
}

export interface EligibilityResult {
  eligible: boolean;
  stagedCount: number;
  buildingCount: number;
  firstStagedStructure: PlannerStructure | null;
}

export interface PlannerStructure {
  flatpackBlueprintUUID: string;
  isBuilt: boolean;
  isStaged: boolean;
  isOnline: boolean;
  buildQueueSequence: number;
  assignedWorkers?: Record<string, boolean>;
}
