using OE2EmpireTracker.Controls;

namespace OE2EmpireTracker
{
    partial class FormBlueprintV2
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.splitMain = new System.Windows.Forms.SplitContainer();
            this.flpSearchList = new System.Windows.Forms.FlowLayoutPanel();
            this.txtFilter = new OE2EmpireTracker.Controls.ValidatedTextBox();
            this.flpFilterPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.flpFilterRow1 = new System.Windows.Forms.FlowLayoutPanel();
            this.lblFilterType = new System.Windows.Forms.Label();
            this.cmbFilterType = new System.Windows.Forms.ComboBox();
            this.lblFilterClass = new System.Windows.Forms.Label();
            this.cmbFilterClass = new System.Windows.Forms.ComboBox();
            this.flpFilterRow2 = new System.Windows.Forms.FlowLayoutPanel();
            this.lblFilterTechLevel = new System.Windows.Forms.Label();
            this.cmbFilterTechLevel = new System.Windows.Forms.ComboBox();
            this.lblFilterEvolution = new System.Windows.Forms.Label();
            this.cmbFilterEvolution = new System.Windows.Forms.ComboBox();
            this.chkFilterEvoAndAbove = new System.Windows.Forms.CheckBox();
            this.btnClearFilters = new System.Windows.Forms.Button();
            this.lvwBlueprints = new System.Windows.Forms.ListView();
            this.colType = new System.Windows.Forms.ColumnHeader();
            this.colName = new System.Windows.Forms.ColumnHeader();
            this.colTechLevel = new System.Windows.Forms.ColumnHeader();
            this.colEvolution = new System.Windows.Forms.ColumnHeader();
            this.colNickName = new System.Windows.Forms.ColumnHeader();
            this.colRefs = new System.Windows.Forms.ColumnHeader();
            this.flpBlueprintData = new System.Windows.Forms.FlowLayoutPanel();
            this.flpIdentity = new System.Windows.Forms.FlowLayoutPanel();
            this.flpNameRow = new System.Windows.Forms.FlowLayoutPanel();
            this.lblName = new System.Windows.Forms.Label();
            this.txtName = new OE2EmpireTracker.Controls.ValidatedTextBox();
            this.flpNickNameRow = new System.Windows.Forms.FlowLayoutPanel();
            this.lblNickName = new System.Windows.Forms.Label();
            this.txtNickName = new OE2EmpireTracker.Controls.ValidatedTextBox();
            this.flpDescriptionRow = new System.Windows.Forms.FlowLayoutPanel();
            this.lblDescription = new System.Windows.Forms.Label();
            this.txtDescription = new OE2EmpireTracker.Controls.ValidatedTextBox();
            this.flpCopyCostRow = new System.Windows.Forms.FlowLayoutPanel();
            this.lblCopyCost = new System.Windows.Forms.Label();
            this.txtCopyCost = new OE2EmpireTracker.Controls.ValidatedTextBox();
            this.flpTypeRow = new System.Windows.Forms.FlowLayoutPanel();
            this.lblBlueprintType = new System.Windows.Forms.Label();
            this.cmbBlueprintType = new System.Windows.Forms.ComboBox();
            this.flpClassRow = new System.Windows.Forms.FlowLayoutPanel();
            this.lblShipClass = new System.Windows.Forms.Label();
            this.cmbShipClass = new System.Windows.Forms.ComboBox();
            this.flpTechLevelRow = new System.Windows.Forms.FlowLayoutPanel();
            this.lblTechLevel = new System.Windows.Forms.Label();
            this.cmbTechLevel = new System.Windows.Forms.ComboBox();
            this.flpEvolutionRow = new System.Windows.Forms.FlowLayoutPanel();
            this.lblEvolution = new System.Windows.Forms.Label();
            this.cmbEvolution = new System.Windows.Forms.ComboBox();
            this.flpBaseBlueprintRow = new System.Windows.Forms.FlowLayoutPanel();
            this.lblBaseBlueprint = new System.Windows.Forms.Label();
            this.txtFilterBaseBlueprint = new OE2EmpireTracker.Controls.ValidatedTextBox();
            this.cmbBaseBlueprint = new System.Windows.Forms.ComboBox();
            this.chkGlobalBlueprint = new System.Windows.Forms.CheckBox();
            this.flpCommands = new System.Windows.Forms.FlowLayoutPanel();
            this.btnNew = new System.Windows.Forms.Button();
            this.btnSave = new System.Windows.Forms.Button();
            this.btnDelete = new System.Windows.Forms.Button();
            this.btnImport = new System.Windows.Forms.Button();
            this.btnImportMarket = new System.Windows.Forms.Button();
            this.tabDetailedData = new System.Windows.Forms.TabControl();
            this.tabPStatistics = new System.Windows.Forms.TabPage();
            this.dgvStatistics = new DataEntryGridView();
            this.colProperty = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colCurrentValue = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.tabPResources = new System.Windows.Forms.TabPage();
            this.pnlResourceButtons = new System.Windows.Forms.FlowLayoutPanel();
            this.btnAddResource = new System.Windows.Forms.Button();
            this.btnDeleteResource = new System.Windows.Forms.Button();
            this.dgvResources = new System.Windows.Forms.DataGridView();
            this.colResource = new System.Windows.Forms.DataGridViewComboBoxColumn();
            this.colAmount = new OE2EmpireTracker.Controls.DataGridViewValidatedTextBoxColumn();
            this.tabPEvolutionGraph = new System.Windows.Forms.TabPage();
            this.pnlEvolutionGraphPlaceholder = new System.Windows.Forms.Panel();
            this.flpPricing = new System.Windows.Forms.FlowLayoutPanel();
            this.lblPricingPlan = new System.Windows.Forms.Label();
            this.cmbPricingPlan = new System.Windows.Forms.ComboBox();
            this.lblComputedPrice = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.splitMain)).BeginInit();
            this.splitMain.Panel1.SuspendLayout();
            this.splitMain.Panel2.SuspendLayout();
            this.splitMain.SuspendLayout();
            this.flpSearchList.SuspendLayout();
            this.flpFilterPanel.SuspendLayout();
            this.flpFilterRow1.SuspendLayout();
            this.flpFilterRow2.SuspendLayout();
            this.flpBlueprintData.SuspendLayout();
            this.flpIdentity.SuspendLayout();
            this.flpNameRow.SuspendLayout();
            this.flpNickNameRow.SuspendLayout();
            this.flpDescriptionRow.SuspendLayout();
            this.flpCopyCostRow.SuspendLayout();
            this.flpTypeRow.SuspendLayout();
            this.flpClassRow.SuspendLayout();
            this.flpTechLevelRow.SuspendLayout();
            this.flpEvolutionRow.SuspendLayout();
            this.flpBaseBlueprintRow.SuspendLayout();
            this.flpCommands.SuspendLayout();
            this.tabDetailedData.SuspendLayout();
            this.tabPStatistics.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvStatistics)).BeginInit();
            this.tabPResources.SuspendLayout();
            this.pnlResourceButtons.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvResources)).BeginInit();
            this.flpPricing.SuspendLayout();
            this.SuspendLayout();
            // splitMain
            this.splitMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitMain.Location = new System.Drawing.Point(0, 0);
            this.splitMain.Name = "splitMain";
            this.splitMain.Panel1.Controls.Add(this.flpSearchList);
            this.splitMain.Panel2.Controls.Add(this.flpBlueprintData);
            this.splitMain.Size = new System.Drawing.Size(1200, 700);
            this.splitMain.SplitterDistance = 380;
            this.splitMain.TabIndex = 0;
            // flpSearchList
            this.flpSearchList.Controls.Add(this.txtFilter);
            this.flpSearchList.Controls.Add(this.flpFilterPanel);
            this.flpSearchList.Controls.Add(this.lvwBlueprints);
            this.flpSearchList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpSearchList.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.flpSearchList.Location = new System.Drawing.Point(0, 0);
            this.flpSearchList.Name = "flpSearchList";
            this.flpSearchList.Padding = new System.Windows.Forms.Padding(4);
            this.flpSearchList.Size = new System.Drawing.Size(380, 700);
            this.flpSearchList.TabIndex = 0;
            this.flpSearchList.WrapContents = false;
            // txtFilter
            this.txtFilter.Location = new System.Drawing.Point(7, 7);
            this.txtFilter.Name = "txtFilter";
            this.txtFilter.Size = new System.Drawing.Size(360, 20);
            this.txtFilter.TabIndex = 0;
            // flpFilterPanel
            this.flpFilterPanel.AutoSize = true;
            this.flpFilterPanel.Controls.Add(this.flpFilterRow1);
            this.flpFilterPanel.Controls.Add(this.flpFilterRow2);
            this.flpFilterPanel.Controls.Add(this.btnClearFilters);
            this.flpFilterPanel.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.flpFilterPanel.Location = new System.Drawing.Point(7, 33);
            this.flpFilterPanel.Name = "flpFilterPanel";
            this.flpFilterPanel.Size = new System.Drawing.Size(360, 80);
            this.flpFilterPanel.TabIndex = 1;
            this.flpFilterPanel.WrapContents = false;
            // flpFilterRow1
            this.flpFilterRow1.AutoSize = true;
            this.flpFilterRow1.Controls.Add(this.lblFilterType);
            this.flpFilterRow1.Controls.Add(this.cmbFilterType);
            this.flpFilterRow1.Controls.Add(this.lblFilterClass);
            this.flpFilterRow1.Controls.Add(this.cmbFilterClass);
            this.flpFilterRow1.Location = new System.Drawing.Point(2, 2);
            this.flpFilterRow1.Margin = new System.Windows.Forms.Padding(2);
            this.flpFilterRow1.Name = "flpFilterRow1";
            this.flpFilterRow1.Size = new System.Drawing.Size(356, 25);
            this.flpFilterRow1.TabIndex = 0;
            // lblFilterType
            this.lblFilterType.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblFilterType.Location = new System.Drawing.Point(2, 4);
            this.lblFilterType.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblFilterType.Name = "lblFilterType";
            this.lblFilterType.Size = new System.Drawing.Size(35, 17);
            this.lblFilterType.TabIndex = 0;
            this.lblFilterType.Text = "Type";
            this.lblFilterType.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // cmbFilterType
            this.cmbFilterType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFilterType.FormattingEnabled = true;
            this.cmbFilterType.Location = new System.Drawing.Point(41, 2);
            this.cmbFilterType.Margin = new System.Windows.Forms.Padding(2);
            this.cmbFilterType.Name = "cmbFilterType";
            this.cmbFilterType.Size = new System.Drawing.Size(130, 21);
            this.cmbFilterType.TabIndex = 1;
            // lblFilterClass
            this.lblFilterClass.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblFilterClass.Location = new System.Drawing.Point(175, 4);
            this.lblFilterClass.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblFilterClass.Name = "lblFilterClass";
            this.lblFilterClass.Size = new System.Drawing.Size(35, 17);
            this.lblFilterClass.TabIndex = 2;
            this.lblFilterClass.Text = "Class";
            this.lblFilterClass.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // cmbFilterClass
            this.cmbFilterClass.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFilterClass.FormattingEnabled = true;
            this.cmbFilterClass.Location = new System.Drawing.Point(214, 2);
            this.cmbFilterClass.Margin = new System.Windows.Forms.Padding(2);
            this.cmbFilterClass.Name = "cmbFilterClass";
            this.cmbFilterClass.Size = new System.Drawing.Size(130, 21);
            this.cmbFilterClass.TabIndex = 3;
            // flpFilterRow2
            this.flpFilterRow2.AutoSize = true;
            this.flpFilterRow2.Controls.Add(this.lblFilterTechLevel);
            this.flpFilterRow2.Controls.Add(this.cmbFilterTechLevel);
            this.flpFilterRow2.Controls.Add(this.lblFilterEvolution);
            this.flpFilterRow2.Controls.Add(this.cmbFilterEvolution);
            this.flpFilterRow2.Controls.Add(this.chkFilterEvoAndAbove);
            this.flpFilterRow2.Location = new System.Drawing.Point(2, 31);
            this.flpFilterRow2.Margin = new System.Windows.Forms.Padding(2);
            this.flpFilterRow2.Name = "flpFilterRow2";
            this.flpFilterRow2.Size = new System.Drawing.Size(356, 25);
            this.flpFilterRow2.TabIndex = 1;
            // lblFilterTechLevel
            this.lblFilterTechLevel.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblFilterTechLevel.Location = new System.Drawing.Point(2, 4);
            this.lblFilterTechLevel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblFilterTechLevel.Name = "lblFilterTechLevel";
            this.lblFilterTechLevel.Size = new System.Drawing.Size(35, 17);
            this.lblFilterTechLevel.TabIndex = 0;
            this.lblFilterTechLevel.Text = "Tech";
            this.lblFilterTechLevel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // cmbFilterTechLevel
            this.cmbFilterTechLevel.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFilterTechLevel.FormattingEnabled = true;
            this.cmbFilterTechLevel.Location = new System.Drawing.Point(41, 2);
            this.cmbFilterTechLevel.Margin = new System.Windows.Forms.Padding(2);
            this.cmbFilterTechLevel.Name = "cmbFilterTechLevel";
            this.cmbFilterTechLevel.Size = new System.Drawing.Size(80, 21);
            this.cmbFilterTechLevel.TabIndex = 1;
            // lblFilterEvolution
            this.lblFilterEvolution.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblFilterEvolution.Location = new System.Drawing.Point(125, 4);
            this.lblFilterEvolution.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblFilterEvolution.Name = "lblFilterEvolution";
            this.lblFilterEvolution.Size = new System.Drawing.Size(25, 17);
            this.lblFilterEvolution.TabIndex = 2;
            this.lblFilterEvolution.Text = "Evo";
            this.lblFilterEvolution.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // cmbFilterEvolution
            this.cmbFilterEvolution.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFilterEvolution.FormattingEnabled = true;
            this.cmbFilterEvolution.Location = new System.Drawing.Point(154, 2);
            this.cmbFilterEvolution.Margin = new System.Windows.Forms.Padding(2);
            this.cmbFilterEvolution.Name = "cmbFilterEvolution";
            this.cmbFilterEvolution.Size = new System.Drawing.Size(60, 21);
            this.cmbFilterEvolution.TabIndex = 3;
            // chkFilterEvoAndAbove
            this.chkFilterEvoAndAbove.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.chkFilterEvoAndAbove.AutoSize = true;
            this.chkFilterEvoAndAbove.Location = new System.Drawing.Point(219, 4);
            this.chkFilterEvoAndAbove.Margin = new System.Windows.Forms.Padding(3);
            this.chkFilterEvoAndAbove.Name = "chkFilterEvoAndAbove";
            this.chkFilterEvoAndAbove.Size = new System.Drawing.Size(78, 17);
            this.chkFilterEvoAndAbove.TabIndex = 4;
            this.chkFilterEvoAndAbove.Text = "And Above";
            this.chkFilterEvoAndAbove.UseVisualStyleBackColor = true;
            // btnClearFilters
            this.btnClearFilters.Location = new System.Drawing.Point(2, 60);
            this.btnClearFilters.Margin = new System.Windows.Forms.Padding(2);
            this.btnClearFilters.Name = "btnClearFilters";
            this.btnClearFilters.Size = new System.Drawing.Size(90, 23);
            this.btnClearFilters.TabIndex = 2;
            this.btnClearFilters.Text = "Clear Filters";
            this.btnClearFilters.UseVisualStyleBackColor = true;
            // lvwBlueprints
            this.lvwBlueprints.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.colType, this.colName, this.colTechLevel, this.colEvolution, this.colNickName, this.colRefs});
            this.lvwBlueprints.FullRowSelect = true;
            this.lvwBlueprints.HideSelection = false;
            this.lvwBlueprints.Location = new System.Drawing.Point(7, 119);
            this.lvwBlueprints.MultiSelect = false;
            this.lvwBlueprints.Name = "lvwBlueprints";
            this.lvwBlueprints.Size = new System.Drawing.Size(360, 570);
            this.lvwBlueprints.TabIndex = 2;
            this.lvwBlueprints.UseCompatibleStateImageBehavior = false;
            this.lvwBlueprints.View = System.Windows.Forms.View.Details;
            this.lvwBlueprints.AllowColumnReorder = true;
            // colType
            this.colType.Text = "Type";
            this.colType.Width = 80;
            // colName
            this.colName.Text = "Name";
            this.colName.Width = 100;
            // colTechLevel
            this.colTechLevel.Text = "TechLevel";
            this.colTechLevel.Width = 60;
            // colEvolution
            this.colEvolution.Text = "Evolution";
            this.colEvolution.Width = 55;
            // colNickName
            this.colNickName.Text = "NickName";
            this.colNickName.Width = 70;
            // colRefs
            this.colRefs.Text = "Refs";
            this.colRefs.Width = 35;
            // flpBlueprintData
            this.flpBlueprintData.Controls.Add(this.flpIdentity);
            this.flpBlueprintData.Controls.Add(this.flpCommands);
            this.flpBlueprintData.Controls.Add(this.tabDetailedData);
            this.flpBlueprintData.Controls.Add(this.flpPricing);
            this.flpBlueprintData.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpBlueprintData.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.flpBlueprintData.Location = new System.Drawing.Point(0, 0);
            this.flpBlueprintData.Name = "flpBlueprintData";
            this.flpBlueprintData.Padding = new System.Windows.Forms.Padding(4);
            this.flpBlueprintData.Size = new System.Drawing.Size(816, 700);
            this.flpBlueprintData.TabIndex = 0;
            this.flpBlueprintData.WrapContents = false;
            // flpIdentity
            this.flpIdentity.AutoSize = true;
            this.flpIdentity.Controls.Add(this.flpNameRow);
            this.flpIdentity.Controls.Add(this.flpNickNameRow);
            this.flpIdentity.Controls.Add(this.flpDescriptionRow);
            this.flpIdentity.Controls.Add(this.flpCopyCostRow);
            this.flpIdentity.Controls.Add(this.flpTypeRow);
            this.flpIdentity.Controls.Add(this.flpClassRow);
            this.flpIdentity.Controls.Add(this.flpTechLevelRow);
            this.flpIdentity.Controls.Add(this.flpEvolutionRow);
            this.flpIdentity.Controls.Add(this.flpBaseBlueprintRow);
            this.flpIdentity.Controls.Add(this.chkGlobalBlueprint);
            this.flpIdentity.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.flpIdentity.Location = new System.Drawing.Point(7, 7);
            this.flpIdentity.Name = "flpIdentity";
            this.flpIdentity.Size = new System.Drawing.Size(800, 270);
            this.flpIdentity.TabIndex = 0;
            // flpNameRow
            this.flpNameRow.AutoSize = true;
            this.flpNameRow.Controls.Add(this.lblName);
            this.flpNameRow.Controls.Add(this.txtName);
            this.flpNameRow.Location = new System.Drawing.Point(2, 2);
            this.flpNameRow.Margin = new System.Windows.Forms.Padding(2);
            this.flpNameRow.Name = "flpNameRow";
            this.flpNameRow.Size = new System.Drawing.Size(309, 24);
            this.flpNameRow.TabIndex = 0;
            // lblName
            this.lblName.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblName.Location = new System.Drawing.Point(2, 3);
            this.lblName.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblName.Name = "lblName";
            this.lblName.Size = new System.Drawing.Size(100, 17);
            this.lblName.TabIndex = 0;
            this.lblName.Text = "Name";
            this.lblName.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // txtName
            this.txtName.Location = new System.Drawing.Point(106, 2);
            this.txtName.Margin = new System.Windows.Forms.Padding(2);
            this.txtName.Name = "txtName";
            this.txtName.Size = new System.Drawing.Size(201, 20);
            this.txtName.TabIndex = 1;
            // flpNickNameRow
            this.flpNickNameRow.AutoSize = true;
            this.flpNickNameRow.Controls.Add(this.lblNickName);
            this.flpNickNameRow.Controls.Add(this.txtNickName);
            this.flpNickNameRow.Location = new System.Drawing.Point(2, 30);
            this.flpNickNameRow.Margin = new System.Windows.Forms.Padding(2);
            this.flpNickNameRow.Name = "flpNickNameRow";
            this.flpNickNameRow.Size = new System.Drawing.Size(309, 24);
            this.flpNickNameRow.TabIndex = 1;
            this.lblNickName.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblNickName.Location = new System.Drawing.Point(2, 3);
            this.lblNickName.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblNickName.Name = "lblNickName";
            this.lblNickName.Size = new System.Drawing.Size(100, 17);
            this.lblNickName.TabIndex = 0;
            this.lblNickName.Text = "Nick Name";
            this.lblNickName.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.txtNickName.Location = new System.Drawing.Point(106, 2);
            this.txtNickName.Margin = new System.Windows.Forms.Padding(2);
            this.txtNickName.Name = "txtNickName";
            this.txtNickName.Size = new System.Drawing.Size(201, 20);
            this.txtNickName.TabIndex = 1;
            // flpDescriptionRow
            this.flpDescriptionRow.AutoSize = true;
            this.flpDescriptionRow.Controls.Add(this.lblDescription);
            this.flpDescriptionRow.Controls.Add(this.txtDescription);
            this.flpDescriptionRow.Location = new System.Drawing.Point(2, 58);
            this.flpDescriptionRow.Margin = new System.Windows.Forms.Padding(2);
            this.flpDescriptionRow.Name = "flpDescriptionRow";
            this.flpDescriptionRow.Size = new System.Drawing.Size(309, 24);
            this.flpDescriptionRow.TabIndex = 2;
            this.lblDescription.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblDescription.Location = new System.Drawing.Point(2, 3);
            this.lblDescription.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblDescription.Name = "lblDescription";
            this.lblDescription.Size = new System.Drawing.Size(100, 17);
            this.lblDescription.TabIndex = 0;
            this.lblDescription.Text = "Description";
            this.lblDescription.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.txtDescription.Location = new System.Drawing.Point(106, 2);
            this.txtDescription.Margin = new System.Windows.Forms.Padding(2);
            this.txtDescription.Name = "txtDescription";
            this.txtDescription.Size = new System.Drawing.Size(201, 20);
            this.txtDescription.TabIndex = 1;
            // flpCopyCostRow
            this.flpCopyCostRow.AutoSize = true;
            this.flpCopyCostRow.Controls.Add(this.lblCopyCost);
            this.flpCopyCostRow.Controls.Add(this.txtCopyCost);
            this.flpCopyCostRow.Location = new System.Drawing.Point(2, 86);
            this.flpCopyCostRow.Margin = new System.Windows.Forms.Padding(2);
            this.flpCopyCostRow.Name = "flpCopyCostRow";
            this.flpCopyCostRow.Size = new System.Drawing.Size(309, 24);
            this.flpCopyCostRow.TabIndex = 3;
            this.lblCopyCost.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblCopyCost.Location = new System.Drawing.Point(2, 3);
            this.lblCopyCost.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblCopyCost.Name = "lblCopyCost";
            this.lblCopyCost.Size = new System.Drawing.Size(100, 17);
            this.lblCopyCost.TabIndex = 0;
            this.lblCopyCost.Text = "Copy Cost";
            this.lblCopyCost.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.txtCopyCost.Location = new System.Drawing.Point(106, 2);
            this.txtCopyCost.Margin = new System.Windows.Forms.Padding(2);
            this.txtCopyCost.Name = "txtCopyCost";
            this.txtCopyCost.Size = new System.Drawing.Size(201, 20);
            this.txtCopyCost.TabIndex = 1;
            // flpTypeRow
            this.flpTypeRow.AutoSize = true;
            this.flpTypeRow.Controls.Add(this.lblBlueprintType);
            this.flpTypeRow.Controls.Add(this.cmbBlueprintType);
            this.flpTypeRow.Location = new System.Drawing.Point(2, 114);
            this.flpTypeRow.Margin = new System.Windows.Forms.Padding(2);
            this.flpTypeRow.Name = "flpTypeRow";
            this.flpTypeRow.Size = new System.Drawing.Size(309, 25);
            this.flpTypeRow.TabIndex = 4;
            this.lblBlueprintType.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblBlueprintType.Location = new System.Drawing.Point(2, 4);
            this.lblBlueprintType.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblBlueprintType.Name = "lblBlueprintType";
            this.lblBlueprintType.Size = new System.Drawing.Size(100, 17);
            this.lblBlueprintType.TabIndex = 0;
            this.lblBlueprintType.Text = "Blueprint Type";
            this.lblBlueprintType.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cmbBlueprintType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbBlueprintType.FormattingEnabled = true;
            this.cmbBlueprintType.Location = new System.Drawing.Point(106, 2);
            this.cmbBlueprintType.Margin = new System.Windows.Forms.Padding(2);
            this.cmbBlueprintType.Name = "cmbBlueprintType";
            this.cmbBlueprintType.Size = new System.Drawing.Size(201, 21);
            this.cmbBlueprintType.TabIndex = 1;
            // flpClassRow
            this.flpClassRow.AutoSize = true;
            this.flpClassRow.Controls.Add(this.lblShipClass);
            this.flpClassRow.Controls.Add(this.cmbShipClass);
            this.flpClassRow.Location = new System.Drawing.Point(2, 143);
            this.flpClassRow.Margin = new System.Windows.Forms.Padding(2);
            this.flpClassRow.Name = "flpClassRow";
            this.flpClassRow.Size = new System.Drawing.Size(309, 25);
            this.flpClassRow.TabIndex = 5;
            this.lblShipClass.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblShipClass.Location = new System.Drawing.Point(2, 4);
            this.lblShipClass.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblShipClass.Name = "lblShipClass";
            this.lblShipClass.Size = new System.Drawing.Size(100, 17);
            this.lblShipClass.TabIndex = 0;
            this.lblShipClass.Text = "Class";
            this.lblShipClass.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cmbShipClass.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbShipClass.FormattingEnabled = true;
            this.cmbShipClass.Location = new System.Drawing.Point(106, 2);
            this.cmbShipClass.Margin = new System.Windows.Forms.Padding(2);
            this.cmbShipClass.Name = "cmbShipClass";
            this.cmbShipClass.Size = new System.Drawing.Size(201, 21);
            this.cmbShipClass.TabIndex = 1;
            // flpTechLevelRow + flpEvolutionRow
            this.flpTechLevelRow.AutoSize = true;
            this.flpTechLevelRow.Controls.Add(this.lblTechLevel);
            this.flpTechLevelRow.Controls.Add(this.cmbTechLevel);
            this.flpTechLevelRow.Location = new System.Drawing.Point(2, 172);
            this.flpTechLevelRow.Margin = new System.Windows.Forms.Padding(2);
            this.flpTechLevelRow.Name = "flpTechLevelRow";
            this.flpTechLevelRow.Size = new System.Drawing.Size(309, 25);
            this.flpTechLevelRow.TabIndex = 6;
            this.lblTechLevel.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblTechLevel.Location = new System.Drawing.Point(2, 4);
            this.lblTechLevel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblTechLevel.Name = "lblTechLevel";
            this.lblTechLevel.Size = new System.Drawing.Size(100, 17);
            this.lblTechLevel.TabIndex = 0;
            this.lblTechLevel.Text = "Tech Level";
            this.lblTechLevel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cmbTechLevel.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbTechLevel.FormattingEnabled = true;
            this.cmbTechLevel.Location = new System.Drawing.Point(106, 2);
            this.cmbTechLevel.Margin = new System.Windows.Forms.Padding(2);
            this.cmbTechLevel.Name = "cmbTechLevel";
            this.cmbTechLevel.Size = new System.Drawing.Size(201, 21);
            this.cmbTechLevel.TabIndex = 1;
            this.flpEvolutionRow.AutoSize = true;
            this.flpEvolutionRow.Controls.Add(this.lblEvolution);
            this.flpEvolutionRow.Controls.Add(this.cmbEvolution);
            this.flpEvolutionRow.Location = new System.Drawing.Point(2, 201);
            this.flpEvolutionRow.Margin = new System.Windows.Forms.Padding(2);
            this.flpEvolutionRow.Name = "flpEvolutionRow";
            this.flpEvolutionRow.Size = new System.Drawing.Size(309, 25);
            this.flpEvolutionRow.TabIndex = 7;
            this.lblEvolution.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblEvolution.Location = new System.Drawing.Point(2, 4);
            this.lblEvolution.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblEvolution.Name = "lblEvolution";
            this.lblEvolution.Size = new System.Drawing.Size(100, 17);
            this.lblEvolution.TabIndex = 0;
            this.lblEvolution.Text = "Evolution";
            this.lblEvolution.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cmbEvolution.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbEvolution.FormattingEnabled = true;
            this.cmbEvolution.Location = new System.Drawing.Point(106, 2);
            this.cmbEvolution.Margin = new System.Windows.Forms.Padding(2);
            this.cmbEvolution.Name = "cmbEvolution";
            this.cmbEvolution.Size = new System.Drawing.Size(201, 21);
            this.cmbEvolution.TabIndex = 1;
            // flpBaseBlueprintRow
            this.flpBaseBlueprintRow.AutoSize = true;
            this.flpBaseBlueprintRow.Controls.Add(this.lblBaseBlueprint);
            this.flpBaseBlueprintRow.Controls.Add(this.txtFilterBaseBlueprint);
            this.flpBaseBlueprintRow.Controls.Add(this.cmbBaseBlueprint);
            this.flpBaseBlueprintRow.Location = new System.Drawing.Point(2, 230);
            this.flpBaseBlueprintRow.Margin = new System.Windows.Forms.Padding(2);
            this.flpBaseBlueprintRow.Name = "flpBaseBlueprintRow";
            this.flpBaseBlueprintRow.Size = new System.Drawing.Size(415, 26);
            this.flpBaseBlueprintRow.TabIndex = 8;
            this.lblBaseBlueprint.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblBaseBlueprint.Location = new System.Drawing.Point(2, 4);
            this.lblBaseBlueprint.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblBaseBlueprint.Name = "lblBaseBlueprint";
            this.lblBaseBlueprint.Size = new System.Drawing.Size(100, 17);
            this.lblBaseBlueprint.TabIndex = 0;
            this.lblBaseBlueprint.Text = "Base Blueprint";
            this.lblBaseBlueprint.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.txtFilterBaseBlueprint.Location = new System.Drawing.Point(107, 3);
            this.txtFilterBaseBlueprint.Name = "txtFilterBaseBlueprint";
            this.txtFilterBaseBlueprint.Size = new System.Drawing.Size(100, 20);
            this.txtFilterBaseBlueprint.TabIndex = 1;
            this.cmbBaseBlueprint.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbBaseBlueprint.FormattingEnabled = true;
            this.cmbBaseBlueprint.Location = new System.Drawing.Point(212, 2);
            this.cmbBaseBlueprint.Margin = new System.Windows.Forms.Padding(2);
            this.cmbBaseBlueprint.Name = "cmbBaseBlueprint";
            this.cmbBaseBlueprint.Size = new System.Drawing.Size(201, 21);
            this.cmbBaseBlueprint.TabIndex = 2;
            // chkGlobalBlueprint
            this.chkGlobalBlueprint.AutoSize = true;
            this.chkGlobalBlueprint.Location = new System.Drawing.Point(3, 261);
            this.chkGlobalBlueprint.Margin = new System.Windows.Forms.Padding(3);
            this.chkGlobalBlueprint.Name = "chkGlobalBlueprint";
            this.chkGlobalBlueprint.Size = new System.Drawing.Size(100, 17);
            this.chkGlobalBlueprint.TabIndex = 9;
            this.chkGlobalBlueprint.Text = "Global Blueprint";
            this.chkGlobalBlueprint.UseVisualStyleBackColor = true;
            // flpCommands
            this.flpCommands.AutoSize = true;
            this.flpCommands.Controls.Add(this.btnNew);
            this.flpCommands.Controls.Add(this.btnSave);
            this.flpCommands.Controls.Add(this.btnDelete);
            this.flpCommands.Controls.Add(this.btnImport);
            this.flpCommands.Controls.Add(this.btnImportMarket);
            this.flpCommands.Location = new System.Drawing.Point(7, 283);
            this.flpCommands.Margin = new System.Windows.Forms.Padding(3);
            this.flpCommands.Name = "flpCommands";
            this.flpCommands.Size = new System.Drawing.Size(800, 29);
            this.flpCommands.TabIndex = 1;
            this.btnNew.Location = new System.Drawing.Point(3, 3);
            this.btnNew.Name = "btnNew";
            this.btnNew.Size = new System.Drawing.Size(75, 23);
            this.btnNew.TabIndex = 0;
            this.btnNew.Text = "New";
            this.btnNew.UseVisualStyleBackColor = true;
            this.btnSave.Location = new System.Drawing.Point(84, 3);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(75, 23);
            this.btnSave.TabIndex = 1;
            this.btnSave.Text = "Save";
            this.btnSave.UseVisualStyleBackColor = true;
            this.btnDelete.Location = new System.Drawing.Point(165, 3);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Size = new System.Drawing.Size(75, 23);
            this.btnDelete.TabIndex = 2;
            this.btnDelete.Text = "Delete";
            this.btnDelete.UseVisualStyleBackColor = true;
            this.btnImport.Location = new System.Drawing.Point(246, 3);
            this.btnImport.Name = "btnImport";
            this.btnImport.Size = new System.Drawing.Size(75, 23);
            this.btnImport.TabIndex = 3;
            this.btnImport.Text = "Import";
            this.btnImport.UseVisualStyleBackColor = true;
            this.btnImportMarket.Location = new System.Drawing.Point(327, 3);
            this.btnImportMarket.Name = "btnImportMarket";
            this.btnImportMarket.Size = new System.Drawing.Size(95, 23);
            this.btnImportMarket.TabIndex = 4;
            this.btnImportMarket.Text = "Import Market";
            this.btnImportMarket.UseVisualStyleBackColor = true;
            // tabDetailedData
            this.tabDetailedData.Controls.Add(this.tabPStatistics);
            this.tabDetailedData.Controls.Add(this.tabPResources);
            this.tabDetailedData.Controls.Add(this.tabPEvolutionGraph);
            this.tabDetailedData.Location = new System.Drawing.Point(7, 318);
            this.tabDetailedData.Margin = new System.Windows.Forms.Padding(3);
            this.tabDetailedData.Name = "tabDetailedData";
            this.tabDetailedData.SelectedIndex = 0;
            this.tabDetailedData.Size = new System.Drawing.Size(800, 320);
            this.tabDetailedData.TabIndex = 2;
            // tabPStatistics + dgvStatistics
            this.tabPStatistics.Controls.Add(this.dgvStatistics);
            this.tabPStatistics.Location = new System.Drawing.Point(4, 22);
            this.tabPStatistics.Margin = new System.Windows.Forms.Padding(2);
            this.tabPStatistics.Name = "tabPStatistics";
            this.tabPStatistics.Padding = new System.Windows.Forms.Padding(2);
            this.tabPStatistics.Size = new System.Drawing.Size(792, 294);
            this.tabPStatistics.TabIndex = 0;
            this.tabPStatistics.Text = "Statistics";
            this.tabPStatistics.UseVisualStyleBackColor = true;
            this.dgvStatistics.AllowUserToAddRows = false;
            this.dgvStatistics.AllowUserToDeleteRows = false;
            this.dgvStatistics.AllowUserToOrderColumns = true;
            this.dgvStatistics.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvStatistics.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.colProperty, this.colCurrentValue });
            this.dgvStatistics.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvStatistics.Location = new System.Drawing.Point(2, 2);
            this.dgvStatistics.Name = "dgvStatistics";
            this.dgvStatistics.previousControl = null;
            this.dgvStatistics.Size = new System.Drawing.Size(788, 290);
            this.dgvStatistics.TabIndex = 0;
            this.colProperty.HeaderText = "Property";
            this.colProperty.Name = "Property";
            this.colProperty.ReadOnly = true;
            this.colProperty.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
            this.colProperty.Width = 200;
            this.colCurrentValue.HeaderText = "CurrentValue";
            this.colCurrentValue.Name = "CurrentValue";
            this.colCurrentValue.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
            this.colCurrentValue.Width = 200;
            // tabPResources
            this.tabPResources.Controls.Add(this.dgvResources);
            this.tabPResources.Controls.Add(this.pnlResourceButtons);
            this.tabPResources.Location = new System.Drawing.Point(4, 22);
            this.tabPResources.Margin = new System.Windows.Forms.Padding(2);
            this.tabPResources.Name = "tabPResources";
            this.tabPResources.Padding = new System.Windows.Forms.Padding(2);
            this.tabPResources.Size = new System.Drawing.Size(792, 294);
            this.tabPResources.TabIndex = 1;
            this.tabPResources.Text = "Resources";
            this.tabPResources.UseVisualStyleBackColor = true;
            this.pnlResourceButtons.Controls.Add(this.btnAddResource);
            this.pnlResourceButtons.Controls.Add(this.btnDeleteResource);
            this.pnlResourceButtons.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pnlResourceButtons.Location = new System.Drawing.Point(2, 263);
            this.pnlResourceButtons.Name = "pnlResourceButtons";
            this.pnlResourceButtons.Size = new System.Drawing.Size(788, 29);
            this.pnlResourceButtons.TabIndex = 1;
            this.btnAddResource.Location = new System.Drawing.Point(3, 3);
            this.btnAddResource.Name = "btnAddResource";
            this.btnAddResource.Size = new System.Drawing.Size(75, 23);
            this.btnAddResource.TabIndex = 0;
            this.btnAddResource.Text = "Add";
            this.btnAddResource.UseVisualStyleBackColor = true;
            this.btnDeleteResource.Location = new System.Drawing.Point(84, 3);
            this.btnDeleteResource.Name = "btnDeleteResource";
            this.btnDeleteResource.Size = new System.Drawing.Size(75, 23);
            this.btnDeleteResource.TabIndex = 1;
            this.btnDeleteResource.Text = "Delete";
            this.btnDeleteResource.UseVisualStyleBackColor = true;
            this.dgvResources.AllowUserToAddRows = false;
            this.dgvResources.AllowUserToDeleteRows = false;
            this.dgvResources.AllowUserToOrderColumns = true;
            this.dgvResources.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvResources.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.colResource, this.colAmount });
            this.dgvResources.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvResources.Location = new System.Drawing.Point(2, 2);
            this.dgvResources.Name = "dgvResources";
            this.dgvResources.Size = new System.Drawing.Size(788, 261);
            this.dgvResources.TabIndex = 0;
            this.colResource.HeaderText = "Resource";
            this.colResource.Name = "Resource";
            this.colResource.Width = 200;
            this.colAmount.HeaderText = "Amount";
            this.colAmount.Name = "Amount";
            this.colAmount.ValidationPattern = OE2EmpireTracker.Controls.ValidatedTextBox.NUMBER_VALIDATION;
            this.colAmount.Width = 100;
            // tabPEvolutionGraph
            this.tabPEvolutionGraph.Controls.Add(this.pnlEvolutionGraphPlaceholder);
            this.tabPEvolutionGraph.Location = new System.Drawing.Point(4, 22);
            this.tabPEvolutionGraph.Margin = new System.Windows.Forms.Padding(2);
            this.tabPEvolutionGraph.Name = "tabPEvolutionGraph";
            this.tabPEvolutionGraph.Padding = new System.Windows.Forms.Padding(2);
            this.tabPEvolutionGraph.Size = new System.Drawing.Size(792, 294);
            this.tabPEvolutionGraph.TabIndex = 2;
            this.tabPEvolutionGraph.Text = "Evolution Graph";
            this.tabPEvolutionGraph.UseVisualStyleBackColor = true;
            this.pnlEvolutionGraphPlaceholder.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlEvolutionGraphPlaceholder.Location = new System.Drawing.Point(2, 2);
            this.pnlEvolutionGraphPlaceholder.Name = "pnlEvolutionGraphPlaceholder";
            this.pnlEvolutionGraphPlaceholder.Size = new System.Drawing.Size(788, 290);
            this.pnlEvolutionGraphPlaceholder.TabIndex = 0;
            // flpPricing
            this.flpPricing.AutoSize = true;
            this.flpPricing.Controls.Add(this.lblPricingPlan);
            this.flpPricing.Controls.Add(this.cmbPricingPlan);
            this.flpPricing.Controls.Add(this.lblComputedPrice);
            this.flpPricing.Location = new System.Drawing.Point(7, 644);
            this.flpPricing.Margin = new System.Windows.Forms.Padding(3);
            this.flpPricing.Name = "flpPricing";
            this.flpPricing.Size = new System.Drawing.Size(800, 25);
            this.flpPricing.TabIndex = 3;
            this.lblPricingPlan.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblPricingPlan.Location = new System.Drawing.Point(2, 4);
            this.lblPricingPlan.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblPricingPlan.Name = "lblPricingPlan";
            this.lblPricingPlan.Size = new System.Drawing.Size(100, 17);
            this.lblPricingPlan.TabIndex = 0;
            this.lblPricingPlan.Text = "Pricing Plan";
            this.lblPricingPlan.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cmbPricingPlan.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbPricingPlan.FormattingEnabled = true;
            this.cmbPricingPlan.Location = new System.Drawing.Point(106, 2);
            this.cmbPricingPlan.Margin = new System.Windows.Forms.Padding(2);
            this.cmbPricingPlan.Name = "cmbPricingPlan";
            this.cmbPricingPlan.Size = new System.Drawing.Size(150, 21);
            this.cmbPricingPlan.TabIndex = 1;
            this.lblComputedPrice.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblComputedPrice.Location = new System.Drawing.Point(260, 4);
            this.lblComputedPrice.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblComputedPrice.Name = "lblComputedPrice";
            this.lblComputedPrice.Size = new System.Drawing.Size(200, 17);
            this.lblComputedPrice.TabIndex = 2;
            this.lblComputedPrice.Text = "";
            this.lblComputedPrice.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // FormBlueprintV2
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1200, 700);
            this.Controls.Add(this.splitMain);
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "FormBlueprintV2";
            this.Text = "Blueprints V2";
            this.splitMain.Panel1.ResumeLayout(false);
            this.splitMain.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitMain)).EndInit();
            this.splitMain.ResumeLayout(false);
            this.flpSearchList.ResumeLayout(false);
            this.flpSearchList.PerformLayout();
            this.flpFilterPanel.ResumeLayout(false);
            this.flpFilterPanel.PerformLayout();
            this.flpFilterRow1.ResumeLayout(false);
            this.flpFilterRow2.ResumeLayout(false);
            this.flpFilterRow2.PerformLayout();
            this.flpBlueprintData.ResumeLayout(false);
            this.flpBlueprintData.PerformLayout();
            this.flpIdentity.ResumeLayout(false);
            this.flpIdentity.PerformLayout();
            this.flpNameRow.ResumeLayout(false);
            this.flpNameRow.PerformLayout();
            this.flpNickNameRow.ResumeLayout(false);
            this.flpNickNameRow.PerformLayout();
            this.flpDescriptionRow.ResumeLayout(false);
            this.flpDescriptionRow.PerformLayout();
            this.flpCopyCostRow.ResumeLayout(false);
            this.flpCopyCostRow.PerformLayout();
            this.flpTypeRow.ResumeLayout(false);
            this.flpClassRow.ResumeLayout(false);
            this.flpTechLevelRow.ResumeLayout(false);
            this.flpEvolutionRow.ResumeLayout(false);
            this.flpBaseBlueprintRow.ResumeLayout(false);
            this.flpBaseBlueprintRow.PerformLayout();
            this.flpCommands.ResumeLayout(false);
            this.tabDetailedData.ResumeLayout(false);
            this.tabPStatistics.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvStatistics)).EndInit();
            this.tabPResources.ResumeLayout(false);
            this.pnlResourceButtons.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvResources)).EndInit();
            this.flpPricing.ResumeLayout(false);
            this.ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.SplitContainer splitMain;
        private System.Windows.Forms.FlowLayoutPanel flpSearchList;
        private OE2EmpireTracker.Controls.ValidatedTextBox txtFilter;
        private System.Windows.Forms.FlowLayoutPanel flpFilterPanel;
        private System.Windows.Forms.FlowLayoutPanel flpFilterRow1;
        private System.Windows.Forms.Label lblFilterType;
        private System.Windows.Forms.ComboBox cmbFilterType;
        private System.Windows.Forms.Label lblFilterClass;
        private System.Windows.Forms.ComboBox cmbFilterClass;
        private System.Windows.Forms.FlowLayoutPanel flpFilterRow2;
        private System.Windows.Forms.Label lblFilterTechLevel;
        private System.Windows.Forms.ComboBox cmbFilterTechLevel;
        private System.Windows.Forms.Label lblFilterEvolution;
        private System.Windows.Forms.ComboBox cmbFilterEvolution;
        private System.Windows.Forms.CheckBox chkFilterEvoAndAbove;
        private System.Windows.Forms.Button btnClearFilters;
        private System.Windows.Forms.ListView lvwBlueprints;
        private System.Windows.Forms.ColumnHeader colType;
        private System.Windows.Forms.ColumnHeader colName;
        private System.Windows.Forms.ColumnHeader colTechLevel;
        private System.Windows.Forms.ColumnHeader colEvolution;
        private System.Windows.Forms.ColumnHeader colNickName;
        private System.Windows.Forms.ColumnHeader colRefs;
        private System.Windows.Forms.FlowLayoutPanel flpBlueprintData;
        private System.Windows.Forms.FlowLayoutPanel flpIdentity;
        private System.Windows.Forms.FlowLayoutPanel flpNameRow;
        private System.Windows.Forms.Label lblName;
        private OE2EmpireTracker.Controls.ValidatedTextBox txtName;
        private System.Windows.Forms.FlowLayoutPanel flpNickNameRow;
        private System.Windows.Forms.Label lblNickName;
        private OE2EmpireTracker.Controls.ValidatedTextBox txtNickName;
        private System.Windows.Forms.FlowLayoutPanel flpDescriptionRow;
        private System.Windows.Forms.Label lblDescription;
        private OE2EmpireTracker.Controls.ValidatedTextBox txtDescription;
        private System.Windows.Forms.FlowLayoutPanel flpCopyCostRow;
        private System.Windows.Forms.Label lblCopyCost;
        private OE2EmpireTracker.Controls.ValidatedTextBox txtCopyCost;
        private System.Windows.Forms.FlowLayoutPanel flpTypeRow;
        private System.Windows.Forms.Label lblBlueprintType;
        private System.Windows.Forms.ComboBox cmbBlueprintType;
        private System.Windows.Forms.FlowLayoutPanel flpClassRow;
        private System.Windows.Forms.Label lblShipClass;
        private System.Windows.Forms.ComboBox cmbShipClass;
        private System.Windows.Forms.FlowLayoutPanel flpTechLevelRow;
        private System.Windows.Forms.Label lblTechLevel;
        private System.Windows.Forms.ComboBox cmbTechLevel;
        private System.Windows.Forms.FlowLayoutPanel flpEvolutionRow;
        private System.Windows.Forms.Label lblEvolution;
        private System.Windows.Forms.ComboBox cmbEvolution;
        private System.Windows.Forms.FlowLayoutPanel flpBaseBlueprintRow;
        private System.Windows.Forms.Label lblBaseBlueprint;
        private OE2EmpireTracker.Controls.ValidatedTextBox txtFilterBaseBlueprint;
        private System.Windows.Forms.ComboBox cmbBaseBlueprint;
        private System.Windows.Forms.CheckBox chkGlobalBlueprint;
        private System.Windows.Forms.FlowLayoutPanel flpCommands;
        private System.Windows.Forms.Button btnNew;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.Button btnDelete;
        private System.Windows.Forms.Button btnImport;
        private System.Windows.Forms.Button btnImportMarket;
        private System.Windows.Forms.TabControl tabDetailedData;
        private System.Windows.Forms.TabPage tabPStatistics;
        private DataEntryGridView dgvStatistics;
        private System.Windows.Forms.DataGridViewTextBoxColumn colProperty;
        private System.Windows.Forms.DataGridViewTextBoxColumn colCurrentValue;
        private System.Windows.Forms.TabPage tabPResources;
        private System.Windows.Forms.FlowLayoutPanel pnlResourceButtons;
        private System.Windows.Forms.Button btnAddResource;
        private System.Windows.Forms.Button btnDeleteResource;
        private System.Windows.Forms.DataGridView dgvResources;
        private System.Windows.Forms.DataGridViewComboBoxColumn colResource;
        private OE2EmpireTracker.Controls.DataGridViewValidatedTextBoxColumn colAmount;
        private System.Windows.Forms.TabPage tabPEvolutionGraph;
        private System.Windows.Forms.Panel pnlEvolutionGraphPlaceholder;
        private System.Windows.Forms.FlowLayoutPanel flpPricing;
        private System.Windows.Forms.Label lblPricingPlan;
        private System.Windows.Forms.ComboBox cmbPricingPlan;
        private System.Windows.Forms.Label lblComputedPrice;
    }
}
