using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OE2EmpireTracker.Baseline
{
    public class ColonyStructureStatus
    {
        /// <summary>
        /// Total Power generated by all online structures in the colony.
        /// </summary>
        public double PowerProvided { get; set; }

        /// <summary>
        /// Total Power demand (capacity load) from all online structures.
        /// </summary>
        public double PowerRequired { get; set; }

        /// <summary>
        /// Total Housing units provided by structures (e.g., Habitation).
        /// </summary>
        public double HabitationProvision { get; set; }

        /// <summary>
        /// Total Habitation capacity required. 
        /// This is typically calculated based on the number of workers assigned to the colony.
        /// Note: In the current implementation, this value is derived from worker counts.
        /// </summary>
        public double HabitationRequired { get; set; }

        /// <summary>
        /// Total Food production provided by food-producing structures.
        /// </summary>
        public double FoodProvision { get; set; }

        /// <summary>
        /// Total Food consumption required. 
        /// Currently calculated based on the total number of colony workers.
        /// </summary>
        public double FoodRequired { get; set; }

        /// <summary>
        /// Amount of entertainment points provided by culture structures.
        /// </summary>
        public double EntertainmentProvided { get; set; }

        /// <summary>
        /// Amount of entertainment required to satisfy colony morale needs (worker dependent).
        /// </summary>
        public double EntertainmentRequired { get; set; }

        /// <summary>
        /// Total storage volume available for cargo in the warehouse structures.
        /// </summary>
        public double WarehouseCapacity { get; set; }

        /// <summary>
        /// Amount of storage required by cargo needs (worker dependent).
        /// </summary>
        public double WarehouseRequired { get; set; }

        public bool UnallocatedBlueCollarPresent { get; set; }
        public bool UnallocatedWhiteCollarPresent { get; set; }
        public bool UnallocatedSpecialistPresent { get; set; }

        /// <summary>
        /// Gets the unallocated worker present flag by detail key.
        /// </summary>
        public bool GetUnallocatedPresent(string detailKey)
        {
            switch (detailKey)
            {
                case "BlueCollarDetail": return UnallocatedBlueCollarPresent;
                case "WhiteCollarDetail": return UnallocatedWhiteCollarPresent;
                case "SpecialistDetail": return UnallocatedSpecialistPresent;
                default: return false;
            }
        }

        /// <summary>
        /// Sets the unallocated worker present flag by detail key.
        /// </summary>
        public void SetUnallocatedPresent(string detailKey, bool value)
        {
            switch (detailKey)
            {
                case "BlueCollarDetail": UnallocatedBlueCollarPresent = value; break;
                case "WhiteCollarDetail": UnallocatedWhiteCollarPresent = value; break;
                case "SpecialistDetail": UnallocatedSpecialistPresent = value; break;
            }
        }

        public ColonyStructureStatus()
        {
            // Default values are set explicitly in CalculateBuilt, but setting properties here is good practice 
            // for clear intent in this context.
            PowerProvided = 0;
            PowerRequired = 0;
            HabitationProvision = 0;
            HabitationRequired = 0;
            FoodProvision = 0;
            FoodRequired = 0;
            EntertainmentProvided = 0;
            EntertainmentRequired = 0;
            WarehouseCapacity = 0;
            WarehouseRequired = 0;
            UnallocatedBlueCollarPresent = false;
            UnallocatedWhiteCollarPresent = false;
            UnallocatedSpecialistPresent = false;
        }
    }
}
