#!/usr/bin/env node
/**
 * code-metrics.js  Parse CodeMetrics.xml and report threshold violations.
 *
 * Usage:
 *   node .kiro/tools/code-metrics.js
 *
 * Reads OE2EmpireTracker/OE2EmpireTracker.Metrics.xml (generated by MSBuild /t:Metrics).
 * Compares per-method and per-type metrics against configurable thresholds.
 * Filters against a baseline of known violations.
 * Reports new violations grouped by metric type.
 *
 * Exit code 0 = no new violations (or XML missing), 1 = new violations found.
 */

const fs = require('fs');
const path = require('path');

const XML_PATH = path.join('OE2EmpireTracker', 'OE2EmpireTracker.Metrics.xml');
const CONFIG_PATH = path.join('.kiro', 'tools', 'code-metrics-config.json');
const BASELINE_PATH = path.join('.kiro', 'tools', 'code-metrics-baseline.json');

const DEFAULTS = {
    maintainabilityIndexMin: 20,
    cyclomaticComplexityMax: 25,
    classCouplingMax: 80,
    depthOfInheritanceMax: 6
};

// --- Config & Baseline loading ---

function loadConfig() {
    try {
        if (!fs.existsSync(CONFIG_PATH)) return DEFAULTS;
        const raw = fs.readFileSync(CONFIG_PATH, 'utf8');
        const parsed = JSON.parse(raw);
        return {
            maintainabilityIndexMin: parsed.maintainabilityIndexMin != null ? parsed.maintainabilityIndexMin : DEFAULTS.maintainabilityIndexMin,
            cyclomaticComplexityMax: parsed.cyclomaticComplexityMax != null ? parsed.cyclomaticComplexityMax : DEFAULTS.cyclomaticComplexityMax,
            classCouplingMax: parsed.classCouplingMax != null ? parsed.classCouplingMax : DEFAULTS.classCouplingMax,
            depthOfInheritanceMax: parsed.depthOfInheritanceMax != null ? parsed.depthOfInheritanceMax : DEFAULTS.depthOfInheritanceMax
        };
    } catch (e) {
        console.log('Warning: could not parse config file, using defaults: ' + e.message);
        return DEFAULTS;
    }
}

function loadBaseline() {
    try {
        if (!fs.existsSync(BASELINE_PATH)) return [];
        const raw = fs.readFileSync(BASELINE_PATH, 'utf8');
        const parsed = JSON.parse(raw);
        return Array.isArray(parsed.violations) ? parsed.violations : [];
    } catch (e) {
        console.log('Warning: could not parse baseline file, treating all violations as new: ' + e.message);
        return [];
    }
}

// --- XML Parsing (state-machine, line-by-line) ---

function extractAttr(line, attrName) {
    const re = new RegExp(attrName + '="([^"]*)"');
    const m = line.match(re);
    if (!m) return null;
    return m[1]
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&amp;/g, '&')
        .replace(/&quot;/g, '"')
        .replace(/&apos;/g, "'");
}

function parseMetricsXml(xmlContent) {
    const lines = xmlContent.split('\n');
    const methods = [];
    const types = [];

    let currentNamespace = '';
    let currentType = '';
    let inMembers = false;
    let currentMember = null;
    let currentMemberMetrics = {};
    let currentTypeMetrics = {};
    let inTypeMetrics = false;
    let inMemberMetrics = false;
    let inAccessors = false;

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim();

        if (line.startsWith('<Namespace ') && !line.startsWith('</')) {
            currentNamespace = extractAttr(line, 'Name') || '';
            continue;
        }
        if (line === '</Namespace>') {
            currentNamespace = '';
            continue;
        }

        if (line.startsWith('<NamedType ') && !line.startsWith('</')) {
            currentType = extractAttr(line, 'Name') || '';
            currentTypeMetrics = {};
            inTypeMetrics = true;
            inMembers = false;
            continue;
        }
        if (line === '</NamedType>') {
            if (currentType) {
                const qn = currentNamespace ? currentNamespace + '.' + currentType : currentType;
                types.push({
                    qualifiedName: qn,
                    namespace: currentNamespace,
                    name: currentType,
                    metrics: currentTypeMetrics
                });
            }
            currentType = '';
            currentTypeMetrics = {};
            inTypeMetrics = false;
            continue;
        }

        if (line === '<Members>') {
            inMembers = true;
            inTypeMetrics = false;
            continue;
        }
        if (line === '</Members>') {
            inMembers = false;
            continue;
        }

        if (line === '<Accessors>') {
            inAccessors = true;
            continue;
        }
        if (line === '</Accessors>') {
            inAccessors = false;
            continue;
        }

        if (inMembers && !inAccessors) {
            if ((line.startsWith('<Method ') || line.startsWith('<Field ') || line.startsWith('<Property ')) && !line.startsWith('</')) {
                const kind = line.startsWith('<Method') ? 'Method' : line.startsWith('<Field') ? 'Field' : 'Property';
                currentMember = {
                    kind: kind,
                    name: extractAttr(line, 'Name') || '',
                    file: extractAttr(line, 'File') || '',
                    line: extractAttr(line, 'Line') || ''
                };
                currentMemberMetrics = {};
                inMemberMetrics = true;
                continue;
            }
            if (line === '</Method>' || line === '</Field>' || line === '</Property>') {
                if (currentMember) {
                    const memberName = currentMember.name;
                    const qn = currentNamespace ? currentNamespace + '.' + memberName : memberName;
                    methods.push({
                        qualifiedName: qn,
                        namespace: currentNamespace,
                        type: currentType,
                        name: memberName,
                        file: currentMember.file,
                        line: currentMember.line,
                        kind: currentMember.kind,
                        metrics: currentMemberMetrics
                    });
                }
                currentMember = null;
                currentMemberMetrics = {};
                inMemberMetrics = false;
                continue;
            }
        }

        if (inMembers && inAccessors) {
            if (line.startsWith('<Method ') && !line.startsWith('</')) {
                currentMember = {
                    kind: 'Method',
                    name: extractAttr(line, 'Name') || '',
                    file: extractAttr(line, 'File') || '',
                    line: extractAttr(line, 'Line') || ''
                };
                currentMemberMetrics = {};
                inMemberMetrics = true;
                continue;
            }
            if (line === '</Method>') {
                if (currentMember) {
                    const memberName = currentMember.name;
                    const qn = currentNamespace ? currentNamespace + '.' + memberName : memberName;
                    methods.push({
                        qualifiedName: qn,
                        namespace: currentNamespace,
                        type: currentType,
                        name: memberName,
                        file: currentMember.file,
                        line: currentMember.line,
                        kind: currentMember.kind,
                        metrics: currentMemberMetrics
                    });
                }
                currentMember = null;
                currentMemberMetrics = {};
                inMemberMetrics = false;
                continue;
            }
        }

        if (line.startsWith('<Metric ')) {
            const metricName = extractAttr(line, 'Name');
            const metricValue = extractAttr(line, 'Value');
            if (metricName && metricValue != null) {
                const numVal = parseInt(metricValue, 10);
                if (!isNaN(numVal)) {
                    if (inMemberMetrics && currentMember) {
                        currentMemberMetrics[metricName] = numVal;
                    } else if (inTypeMetrics && currentType && !inMembers) {
                        currentTypeMetrics[metricName] = numVal;
                    }
                }
            }
            continue;
        }
    }

    return { methods, types };
}

// --- Threshold checking ---

function checkViolations(methods, types, config, baseline) {
    const violations = [];
    const baselineSet = new Set();
    for (const b of baseline) {
        baselineSet.add(b.metric + '::' + b.element);
    }

    for (const m of methods) {
        const mi = m.metrics.MaintainabilityIndex;
        const cc = m.metrics.CyclomaticComplexity;
        const sl = m.metrics.SourceLines || 0;
        const el = m.metrics.ExecutableLines || 0;

        if (mi != null && mi < config.maintainabilityIndexMin) {
            violations.push({
                metric: 'MaintainabilityIndex',
                element: m.qualifiedName,
                value: mi,
                threshold: config.maintainabilityIndexMin,
                sourceLines: sl,
                executableLines: el,
                isBaselined: baselineSet.has('MaintainabilityIndex::' + m.qualifiedName),
                level: 'method'
            });
        }

        if (cc != null && cc > config.cyclomaticComplexityMax) {
            violations.push({
                metric: 'CyclomaticComplexity',
                element: m.qualifiedName,
                value: cc,
                threshold: config.cyclomaticComplexityMax,
                sourceLines: sl,
                executableLines: el,
                isBaselined: baselineSet.has('CyclomaticComplexity::' + m.qualifiedName),
                level: 'method'
            });
        }
    }

    for (const t of types) {
        const coupling = t.metrics.ClassCoupling;
        const doi = t.metrics.DepthOfInheritance;
        const sl = t.metrics.SourceLines || 0;
        const el = t.metrics.ExecutableLines || 0;

        if (coupling != null && coupling > config.classCouplingMax) {
            violations.push({
                metric: 'ClassCoupling',
                element: t.qualifiedName,
                value: coupling,
                threshold: config.classCouplingMax,
                sourceLines: sl,
                executableLines: el,
                isBaselined: baselineSet.has('ClassCoupling::' + t.qualifiedName),
                level: 'type'
            });
        }

        if (doi != null && doi > config.depthOfInheritanceMax) {
            violations.push({
                metric: 'DepthOfInheritance',
                element: t.qualifiedName,
                value: doi,
                threshold: config.depthOfInheritanceMax,
                sourceLines: sl,
                executableLines: el,
                isBaselined: baselineSet.has('DepthOfInheritance::' + t.qualifiedName),
                level: 'type'
            });
        }
    }

    return violations;
}

// --- Output formatting ---

function formatOutput(violations) {
    console.log('=== Code Metrics Audit ===');
    console.log('');

    const groups = {};
    for (const v of violations) {
        if (!groups[v.metric]) groups[v.metric] = [];
        groups[v.metric].push(v);
    }

    const metricInfo = {
        MaintainabilityIndex: 'min: ',
        CyclomaticComplexity: 'max: ',
        ClassCoupling: 'max: ',
        DepthOfInheritance: 'max: '
    };
    const metricAbbrev = {
        MaintainabilityIndex: 'MI',
        CyclomaticComplexity: 'CC',
        ClassCoupling: 'CP',
        DepthOfInheritance: 'DI'
    };

    const order = ['MaintainabilityIndex', 'CyclomaticComplexity', 'ClassCoupling', 'DepthOfInheritance'];

    for (const metric of order) {
        const items = groups[metric];
        if (!items || items.length === 0) continue;

        const prefix = metricInfo[metric] || '';
        const abbrev = metricAbbrev[metric] || metric;
        console.log('--- ' + metric + ' (' + prefix + items[0].threshold + ') ---');

        for (const v of items) {
            const tag = v.isBaselined ? '  BASELINE: ' : '  VIOLATION:';
            const detail = ' ' + v.element + ' ' + abbrev + '=' + v.value + ' (threshold: ' + v.threshold + ') [SL:' + v.sourceLines + ' EL:' + v.executableLines + ']';
            console.log(tag + detail);
        }
        console.log('');
    }

    const newCount = violations.filter(v => !v.isBaselined).length;
    console.log(newCount + ' findings');
    return newCount;
}

// --- Main ---

function main() {
    if (!fs.existsSync(XML_PATH)) {
        console.log('=== Code Metrics Audit ===');
        console.log('');
        console.log('CodeMetrics.xml not found at ' + XML_PATH + ' -- skipping metrics analysis.');
        console.log('Run MSBuild /t:Metrics to generate the file.');
        console.log('');
        console.log('0 findings');
        process.exit(0);
    }

    let xmlContent;
    try {
        xmlContent = fs.readFileSync(XML_PATH, 'utf8');
    } catch (e) {
        console.log('=== Code Metrics Audit ===');
        console.log('');
        console.log('Error reading ' + XML_PATH + ': ' + e.message);
        console.log('');
        console.log('0 findings');
        process.exit(0);
    }

    let parsed;
    try {
        parsed = parseMetricsXml(xmlContent);
    } catch (e) {
        console.log('=== Code Metrics Audit ===');
        console.log('');
        console.log('Error parsing XML: ' + e.message);
        console.log('');
        console.log('0 findings');
        process.exit(0);
    }

    const config = loadConfig();
    const baseline = loadBaseline();
    const violations = checkViolations(parsed.methods, parsed.types, config, baseline);
    const newCount = formatOutput(violations);

    process.exit(newCount > 0 ? 1 : 0);
}

main();