using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OE2EmpireTracker.Models
{
    public class ColonyStructureStatus
    {
        public ColonyStructureStatus()
        {
            // Default values are set explicitly in CalculateBuilt, but setting properties here is good practice
            // for clear intent in this context.
            PowerProvided = 0m;
            PowerRequired = 0m;
            HabitationProvision = 0m;
            HabitationRequired = 0m;
            FoodProvision = 0m;
            FoodRequired = 0m;
            EntertainmentProvided = 0m;
            EntertainmentRequired = 0m;
            WarehouseCapacity = 0m;
            WarehouseRequired = 0m;
            UnallocatedBlueCollarPresent = false;
            UnallocatedWhiteCollarPresent = false;
            UnallocatedSpecialistPresent = false;
        }

        /// <summary>
        /// Total Power generated by all online structures in the colony.
        /// </summary>
        public decimal PowerProvided { get; set; }

        /// <summary>
        /// Total Power demand (capacity load) from all online structures.
        /// </summary>
        public decimal PowerRequired { get; set; }

        /// <summary>
        /// Total Housing units provided by structures (e.g., Habitation).
        /// </summary>
        public decimal HabitationProvision { get; set; }

        /// <summary>
        /// Total Habitation capacity required.
        /// This is typically calculated based on the number of workers assigned to the colony.
        /// Note: In the current implementation, this value is derived from worker counts.
        /// </summary>
        public decimal HabitationRequired { get; set; }

        /// <summary>
        /// Total Food production provided by food-producing structures.
        /// </summary>
        public decimal FoodProvision { get; set; }

        /// <summary>
        /// Total Food consumption required.
        /// Currently calculated based on the total number of colony workers.
        /// </summary>
        public decimal FoodRequired { get; set; }

        /// <summary>
        /// Amount of entertainment points provided by culture structures.
        /// </summary>
        public decimal EntertainmentProvided { get; set; }

        /// <summary>
        /// Amount of entertainment required to satisfy colony morale needs (worker dependent).
        /// </summary>
        public decimal EntertainmentRequired { get; set; }

        /// <summary>
        /// Total storage volume available for cargo in the warehouse structures.
        /// </summary>
        public decimal WarehouseCapacity { get; set; }

        /// <summary>
        /// Amount of storage required by cargo needs (worker dependent).
        /// </summary>
        public decimal WarehouseRequired { get; set; }

        public bool UnallocatedBlueCollarPresent { get; set; }

        public bool UnallocatedWhiteCollarPresent { get; set; }

        public bool UnallocatedSpecialistPresent { get; set; }

        /// <summary>
        /// Gets the unallocated worker present flag by detail key.
        /// </summary>
        public bool GetUnallocatedPresent(string detailKey)
        {
            switch (detailKey)
            {
                case Constants.GameConstants.WorkerIdBlueCollar: return UnallocatedBlueCollarPresent;
                case Constants.GameConstants.WorkerIdWhiteCollar: return UnallocatedWhiteCollarPresent;
                case Constants.GameConstants.WorkerIdSpecialist: return UnallocatedSpecialistPresent;
                default: return false;
            }
        }

        /// <summary>
        /// Sets the unallocated worker present flag by detail key.
        /// </summary>
        public void SetUnallocatedPresent(string detailKey, bool value)
        {
            switch (detailKey)
            {
                case Constants.GameConstants.WorkerIdBlueCollar: UnallocatedBlueCollarPresent = value; break;
                case Constants.GameConstants.WorkerIdWhiteCollar: UnallocatedWhiteCollarPresent = value; break;
                case Constants.GameConstants.WorkerIdSpecialist: UnallocatedSpecialistPresent = value; break;
            }
        }
    }
}
