namespace OE2EmpireTracker.Models
{
    /// <summary>
    /// Represents the incremental resource contribution of a single colony structure.
    /// Used for O(1) single-structure status recalculation: subtract old delta, add new delta.
    /// </summary>
    public class StructureStatusDelta
    {
        /// <summary>Power generated by this structure (only if online).</summary>
        public decimal PowerProvided { get; set; }

        /// <summary>Power consumed by this structure (only if online).</summary>
        public decimal PowerRequired { get; set; }

        /// <summary>Habitation units provided by this structure (only if online).</summary>
        public decimal HabitationProvision { get; set; }

        /// <summary>Food production from this structure (accumulates regardless of online state).</summary>
        public decimal FoodProvision { get; set; }

        /// <summary>Entertainment points provided by this structure (only if online).</summary>
        public decimal EntertainmentProvided { get; set; }

        /// <summary>Warehouse storage capacity from this structure (only if online).</summary>
        public decimal WarehouseCapacity { get; set; }

        /// <summary>Number of assigned workers on this structure.</summary>
        public int WorkerCount { get; set; }

        /// <summary>Number of unallocated workers contributed by this structure.</summary>
        public int UnallocatedCount { get; set; }
    }
}
