<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>OE2EmpireTracker.Common</RootNamespace>
    <AssemblyName>OE2EmpireTracker.Common</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Xml.SgmlReader" Version="1.8.30" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLog" Version="5.3.4" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="Polly" Version="7.2.4" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OE2EmpireTracker" />
    <InternalsVisibleTo Include="OE2EmpireTracker.Tests" />
    <InternalsVisibleTo Include="OE2EmpireTracker.Server" />
    <InternalsVisibleTo Include="OE2EmpireTracker.Server.Tests" />
    <InternalsVisibleTo Include="OE2EmpireTracker.Desktop" />
  </ItemGroup>

</Project>
