namespace OE2EmpireTracker.Models
{
    /// <summary>
    /// Represents the incremental resource contribution of a single colony structure.
    /// Used for O(1) single-structure status recalculation: subtract old delta, add new delta.
    /// </summary>
    public class StructureStatusDelta
    {
        /// <summary>Power generated by this structure (only if online).</summary>
        public decimal PowerProvided;

        /// <summary>Power consumed by this structure (only if online).</summary>
        public decimal PowerRequired;

        /// <summary>Habitation units provided by this structure (only if online).</summary>
        public decimal HabitationProvision;

        /// <summary>Food production from this structure (accumulates regardless of online state).</summary>
        public decimal FoodProvision;

        /// <summary>Entertainment points provided by this structure (only if online).</summary>
        public decimal EntertainmentProvided;

        /// <summary>Warehouse storage capacity from this structure (only if online).</summary>
        public decimal WarehouseCapacity;

        /// <summary>Number of assigned workers on this structure.</summary>
        public int WorkerCount;

        /// <summary>Number of unallocated workers contributed by this structure.</summary>
        public int UnallocatedCount;
    }
}
