import { useState, useMemo, useCallback } from 'react';
import { useShipTemplates, useTemplateMutations } from '../../api/hooks/useShipTemplates';
import { useBlueprints } from '../../api/hooks/useBlueprints';
import { useBaseline } from '../../api/hooks/useBaseline';
import { useAuthStore } from '../../auth/store';
import { MasterDetailLayout } from '../../components/common/MasterDetailLayout';
import { FilteredDropdown } from '../../components/common/FilteredDropdown';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { RetryableError } from '../../components/common/RetryableError';
import { EmptyState } from '../../components/common/EmptyState';
import { ShipStatsPanel } from '../../components/domain/ShipStatsPanel';
import type { ShipTemplate, TemplateSlot, Blueprint, ShipClassDef, SlotDefinition } from '../../api/types/domain';
